# Generated by Django 4.1.1 on 2022-09-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('Contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('rol_usuario', models.CharField(max_length=100, verbose_name='rol_usuario')),
            ],
        ),
    ]
