# Generated by Django 4.1.1 on 2022-10-03 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('Cedula', models.CharField(max_length=100, verbose_name='Cedula')),
                ('Celular', models.CharField(max_length=100, verbose_name='Celular')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_paciente_id', to='hospitalApp.usuario')),
            ],
        ),
    ]
